export const mappings = {
    type: {
        'Định dạng': '',
        'Phim bộ': 'tv',
        'Phim lẻ': 'movie',
    },
    sort_by: {
        'Sắp xếp': '',
        'Số phiếu bầu': 'vote_count.desc',
        'Đánh giá': 'vote_average.desc',
        'Lượt xem': 'popularity.desc',
    },
    with_genres: {
        'Tất cả thể loại': '',
        'Hành động': '28',
        'Hoạt hình': '16',
        'Hài kịch': '35',
        'Tội phạm': '80',
        'Tài liệu': '99',
        'Gia đình': '10751',
        'Lịch sử': '36',
        'Bí ẩn': '9648',
        'Lãng mạn': '10749',
    },
    with_origin_country: {
        'Tất cả quốc gia': '',
        'Nhật Bản': 'JP',
        'Hàn Quốc': 'KR',
        'Trung Quốc': 'CN',
        Mỹ: 'US',
        Anh: 'GB',
        Pháp: 'FR',
        Đức: 'DE',
        'Ấn Độ': 'IN',
        Ý: 'IT',
        'Tây Ban Nha': 'ES',
        Canada: 'CA',
        Úc: 'AU',
        'Việt Nam': 'VN',
    },
};

export const filters = [
    {
        key: 'sort_by',
        options: ['Sắp xếp', 'Số phiếu bầu', 'Đánh giá', 'Lượt xem'],
    },
    {
        key: 'type',
        options: ['Định dạng', 'Phim bộ', 'Phim lẻ'],
    },
    {
        key: 'with_genres',
        options: [
            'Tất cả thể loại',
            'Hành động',
            'Hoạt hình',
            'Hài kịch',
            'Tội phạm',
            'Tài liệu',
            'Gia đình',
            'Lịch sử',
            'Bí ẩn',
            'Lãng mạn',
        ],
    },
    {
        key: 'with_origin_country',
        options: [
            'Tất cả quốc gia',
            'Việt Nam',
            'Nhật Bản',
            'Hàn Quốc',
            'Trung Quốc',
            'Mỹ',
            'Anh',
            'Pháp',
            'Đức',
            'Ấn Độ',
            'Ý',
            'Tây Ban Nha',
            'Canada',
            'Úc',
        ],
    },
    {
        key: 'primary_release_year',
        options: ['Năm', '2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018'],
    },
];
